# Site settings
title: Code || Code Not
email: chronicole@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codeorcodenot.com" # the base hostname & protocol for your site
twitter_username: chronicole
github_username:  chronicole

# Build settings
markdown: kramdown
